#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.
set -x  # All executed commands are printed to the terminal

aptitude update ; aptitude install -y obfs4proxy

mkdir -p /tor
cp /tmp/contents/static/envvars /tor
cp /tmp/contents/static/obfsproxy /usr/local/bin

sed -i '$i obfsproxy &' /usr/local/boot

rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.aptitude /root/.wget-hsts

